import { RecipeDetails } from "./types";

export const MOCK_RECIPES: RecipeDetails[] = [
  {
    id: "r_001",
    title: "Mediterranean Chickpea Bowl",
    cuisine: "Mediterranean",
    country: "Greece",
    calories: 510,
    dietaryTags: ["vegetarian", "high-protein"],
    description: "Lemony chickpeas, quinoa, and roasted veggies with tahini drizzle.",
    ingredients: [
      "1 cup cooked chickpeas",
      "1 cup cooked quinoa",
      "1 zucchini",
      "1 red pepper",
      "2 tbsp tahini",
      "1 lemon",
    ],
    steps: [
      "Roast chopped vegetables at 200°C for 20 minutes.",
      "Warm chickpeas with olive oil and spices.",
      "Assemble quinoa, vegetables, and chickpeas in a bowl.",
      "Whisk tahini + lemon + water and drizzle over bowl.",
    ],
    cookTimeMinutes: 30,
    servings: 2,
  },
  {
    id: "r_002",
    title: "Thai Coconut Curry Noodles",
    cuisine: "Thai",
    country: "Thailand",
    calories: 620,
    dietaryTags: ["dairy-free"],
    description: "Rice noodles in aromatic red coconut curry with basil.",
    ingredients: ["rice noodles", "coconut milk", "red curry paste", "broccoli", "basil"],
    steps: ["Boil noodles.", "Simmer curry base.", "Add vegetables and finish with basil."],
    cookTimeMinutes: 25,
    servings: 2,
  },
  {
    id: "r_003",
    title: "Grilled Salmon with Herbed Yogurt",
    cuisine: "Nordic",
    country: "Norway",
    calories: 480,
    dietaryTags: ["gluten-free", "high-protein"],
    description: "Seared salmon fillet with dill yogurt and cucumber salad.",
    ingredients: ["salmon fillet", "greek yogurt", "dill", "cucumber", "lemon"],
    steps: ["Season and grill salmon.", "Mix yogurt, dill, and lemon.", "Serve with cucumber salad."],
    cookTimeMinutes: 22,
    servings: 2,
  },
  {
    id: "r_004",
    title: "Vegan Lentil Bolognese",
    cuisine: "Italian",
    country: "Italy",
    calories: 540,
    dietaryTags: ["vegan", "dairy-free"],
    description: "Rich tomato-lentil ragù over whole wheat pasta.",
    ingredients: ["lentils", "tomato passata", "carrot", "onion", "whole wheat pasta"],
    steps: ["Sauté aromatics.", "Simmer lentils in tomato sauce.", "Boil pasta and combine."],
    cookTimeMinutes: 35,
    servings: 4,
  },
  {
    id: "r_005",
    title: "Paneer Tikka Wrap",
    cuisine: "Indian",
    country: "India",
    calories: 590,
    dietaryTags: ["vegetarian"],
    description: "Spiced paneer and peppers rolled in warm flatbread.",
    ingredients: ["paneer", "yogurt", "garam masala", "bell pepper", "flatbread"],
    steps: ["Marinate paneer.", "Grill paneer and peppers.", "Assemble wraps with chutney."],
    cookTimeMinutes: 28,
    servings: 2,
  },
  {
    id: "r_006",
    title: "Chicken Souvlaki Plate",
    cuisine: "Mediterranean",
    country: "Greece",
    calories: 650,
    dietaryTags: ["high-protein"],
    description: "Skewered chicken with rice, salad, and garlic sauce.",
    ingredients: ["chicken breast", "oregano", "rice", "tomatoes", "garlic yogurt"],
    steps: ["Marinate chicken.", "Skewer and grill.", "Serve with rice and salad."],
    cookTimeMinutes: 40,
    servings: 3,
  },
];
